//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSave.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.InteropServices;
    using System.Runtime.InteropServices.ComTypes;

    public partial class Img_table
    {
        public int img_id { get; set; }
        //[AllowFileSize(FILETIME = 5 * 1024 * 1024, ErrorMessage = "Maximum allowed file size is 5 MB")]
        public byte[] picture { get; set; }
        [Required]
       // [RegularExpression("^[a-zA-Z0-9]*$", ErrorMessage = "Only Alphanumerics allowed.")]
        public string img_name { get; set; }
        public string contenttype { get; set; }
    }
}
